version: '3'

services:
  webhook:
    container_name: emetteur_notifs
    build: .
    env_file:
      - .env
    ports:
      - "${WEBHOOK_PORT}:${WEBHOOK_PORT}"
    volumes:
      - ./webhooks.log:/app/webhooks.log
    environment:
      - PORT_WEBHOOK=${WEBHOOK_PORT}
