services:
  flask_app:
    container_name: emetteur_notifs
    build: .
    env_file:
      - .env
    ports:
      - "${WEBHOOK_PORT}:${WEBHOOK_PORT}"
    volumes:
      - .:/app  # reload dynamique
    environment:
      - FLASK_ENV=development  # permet auto-reload pour Flask
      - FLASK_APP=app.py
      - WEBHOOK_PORT=${WEBHOOK_PORT}
    command: flask --debug run --host=0.0.0.0 --port=${WEBHOOK_PORT}
